Wandalen/wTools

staging/wTools.s

mapExtend,
mapKeys,
mapValues,
mapPairs,
mapOwn,
mapSame,
mapContain,
arraySlice.

documents:

---

staging/wTools.s
staging/z.tests/Map.test.s

a document mapBut and a test mapKeys

---

staging/wTools.s

Added description for arrayOrNumber, arraySelect, arrayIron, arrayAppendMerging and arrayPrependMerging methods.

Added description

---

staging/wTools.s

Added some changes from Array* inaccuracies

Array* inaccuracies

---

staging/wTools.s

Added descriptions for arrayAppendOnceMerging, arrayPrependOnceMerging, arrayElementsSwap and arrayRemovedOnce methods

Arrays descriptions

---

sample/SampleRegExp.js
staging/dwtools/abase/layer1.test/Regexp.test.s

- _._regexpTest test routine
- _.regexpTestAll test routine
- _.regexpTestAny test routine
- _.regexpTestNone test routine

Regexp test routines

---

sample/SampleRegExp.js
staging/dwtools/abase/layer1.test/Regexp.test.s
staging/dwtools/abase/layer1/aFundamental.s

Test routines for:
- regexpTest
- regexpsTestAll
- regexpsTestAny
- regexpsTestNone

Reg Exp test routines

---

sample/SampleString.js
staging/dwtools/abase/layer1/aFundamental.s
staging/dwtools/abase/layer2.test/StringTools.test.s
staging/dwtools/abase/layer2/fStringTools.s

- strRemoveBegin test routine improvements
- strRemoveEnd test routine improvements
- _strEndOf corrected
- strReplaceBegin method and test routine improvements
- strReplaceEnd method and test routine improvements
- strPrependOnce method and test routine improvements
- strAppendOnce method and test routine improvements

String test routines coverage

---

sample/SampleString.js
staging/dwtools/abase/layer2.test/StringTools.test.s
staging/dwtools/abase/layer2/fStringTools.s

Methods covered:
- strStrip : strStrip,
- strStripLeft : strStripLeft,
- strStripRight : strStripRight,
- strRemoveAllSpaces : strRemoveAllSpaces,
- strStripEmptyLines : strStripEmptyLines,
- strSub : strSub,
- strDup : strDup,
- strJoin : strJoin,
- strUnjoin : strUnjoin,

String methods coverge

---

doc/ArrayRoutines.md
proto/dwtools/abase/l0/fLong.s
proto/dwtools/abase/l1.test/Array.test.s
sample/SampleArray.js

- Corrections in ArrayRoutines.md

Array improvements

---

doc/ArrayFamily.md
proto/dwtools/abase/l0/fLong.s
proto/dwtools/abase/l1.test/Array.test.s
sample/SampleArrayFlatten.js
sample/SampleArrayPrepend.js
sample/SampleArrayReplace.js

_.arrayCountElement test routine improved
_.arrayCountTotal test routine + description + assert
_.arrayAppend* missing routines created ( + test routines )
_.arrayFlattenedOnceStrictly + corrections in _.arrayFlatten*
_.arrayReplace* missing routines created ( + test routines )
_.arrayPrepend* missing routines created ( + test routines )

_.arrayCountElement/Total test routines + missing routines

---

proto/dwtools/abase/l0.test/Long.test.s

Bug in method longDescriptor.from 
https://github.com/Wandalen/wTools/blob/master/proto/dwtools/abase/l0/l8/gLong.s#L729

Added test-routine and cases

---

proto/wtools/abase/l0.test/Container.test.s
proto/wtools/abase/l0.test/Entity.test.s

…ntity.test.s` and `Container.test.s`

Fix autoreplacing regressions

---

proto/Integration.test.ss

…mprove test routine `productionSuitability` for browser samples

Improve integration test for production versions of modules

---

proto/wtools/abase/l0/l1.test/Buffer.test.s
proto/wtools/abase/l0/l1/Buffer.s

- Work in progress to find more optimized routines.

READY: Optimizing _.bufferAny.is()

---

proto/wtools/abase/l0/l3.test/Set.test.s

1. lengthOf
2. hasKey
3. hasCardinal
4. keyWithCardinal
5. cardinalWithKey

READY : Set routines

---

module/move/wca/Cargo.toml
rust/impl/ca/ca/command.rs
rust/impl/ca/ca/commands_aggregator.rs
rust/impl/ca/ca/instruction.rs
rust/impl/former/meta/former_impl.rs
rust/impl/former/meta/lib_common.rs
rust/test/former/all/alias.rs
rust/test/former/all/wtools_hashmap_without_parameter.rs
rust/test/former/all/wtools_vector_without_parameter.rs
rust/test/former/common_front_test.rs
rust/test/former/former_front_tests.rs

READY : Update former usage

---

rust/test/publisher/inc/publisher_test.rs

READY : Fix publisher test for windows

---

rust/impl/ca/ca/commands_aggregator.rs
rust/impl/publisher/wpublisher_entry.rs
rust/impl/test/wtest_entry.rs
rust/test/dt/type_constructor/dynamic/make/make_too_many.rs
rust/test/dt/type_constructor/dynamic/make/make_too_many.stderr
rust/test/dt/type_constructor/pair/homo_pair_double_difinition_test.stderr
rust/test/publisher/inc/publisher_test.rs

[Commands aggregator](https://github.com/Wandalen/wTools/commit/0df74a1c9a3ce9d5a6beefef5f9f2050071e936d) must be reviewed.
Here was task which implements logger but it was implemented incorrect(imho) and breaks output for user

NOT READY : Fixes to pass all tests

---

module/move/wca/src/ca/executor/converter.rs
module/move/wca/src/ca/executor/execute/command.rs
module/move/wca/src/ca/executor/executor.rs
module/move/wca/src/ca/grammar/converter.rs
module/move/wca/src/ca/grammar/types.rs
module/move/wca/src/ca/parser/entities.rs
module/move/wca/src/lib.rs
module/move/wca/tests/inc/adapter.rs
module/move/wca/tests/inc/commands_aggregator/basic.rs
module/move/wca/tests/inc/executor/namespace.rs
module/move/wca/tests/inc/executor/program.rs
module/move/wca/tests/inc/grammar/types.rs
module/move/wca/tests/inc/parser/command.rs
module/move/wca/tests/inc/parser/namespace.rs
module/move/wca/tests/inc/parser/program.rs

READY: WCA fix

---

module/move/willbe/src/command/list.rs
module/move/willbe/src/command/publish.rs
module/move/willbe/src/commands/init.rs
module/move/willbe/src/endpoint/list.rs

Partially overrides #1001 
`.list ./` - should work

READY: (willbe) `.list` command should work with directories instead of glob

---

.github/workflows/AutoPr.yml

READY: Fix workflow `AutoPr`

---

module/move/wca/Cargo.toml
module/move/wca/src/ca/commands_aggregator/help.rs
module/move/wca/tests/assets/wca_hello_test/Cargo.toml
module/move/wca/tests/assets/wca_hello_test/src/main.rs
module/move/wca/tests/inc/commands_aggregator/help.rs
module/move/wca/tests/inc/commands_aggregator/mod.rs

Now look like this:
```cmd
Subjects:
- Subject [String] ?
Properties:
property - simple property [String] ?
```

READY (WCA): marker for optional params

---

module/move/wca/Readme.md
module/move/wca/src/ca/aggregator.rs
module/move/wca/src/ca/executor/routine.rs
module/move/wca/src/ca/grammar/command.rs
module/move/wca/src/ca/help.rs
module/move/wca/src/ca/input.rs
module/move/wca/tests/assets/wca_hello_test/src/main.rs
module/move/willbe/tests/inc/endpoints/tests_run.rs

The import statements across multiple files in the WCA module have been updated for better readability and consistency. In specific, imports from the command.rs, help.rs, aggregator.rs, input.rs, and routine.rs files have been modified. Also, a minor update has been done on test parameters in tests_run.rs.

READY : (wca, willbe): Update import statements in WCA module

---

module/move/willbe/src/command/mod.rs
module/move/willbe/src/command/workspace_new.rs
module/move/willbe/src/endpoint/workspace_new.rs
module/move/willbe/template/workspace/Cargo.hbs
module/move/willbe/tests/inc/endpoints/workspace_new.rs

Now should call like this:
```shell
will .workspace.new repository_url:"https://github.com/Username/TestProject" branches:"master","alpha"
```

READY(willbe) : add properties to `workspace.new`

---

module/move/willbe/src/test.rs
module/move/willbe/tests/inc/endpoints/tests_run.rs

READY(willbe) :fmt & fix

---

module/core/former/Readme.md

Fixed doc test in former's `Readme.md`

READY : Fix doc test in Readme.md

---

module/move/willbe/Cargo.toml
module/move/willbe/src/entity/test.rs

All pass viwe:
* `[ ]` is with none features
Some fail view:
... other out from console

NOT READY (willbe/`.test`) : make test report table & change output on fail's

---

module/move/willbe/src/entity/test.rs

change description on spinner
remove border

READY : after review fix

---

module/move/wca/src/ca/grammar/types.rs
module/move/willbe/src/command/publish.rs
module/move/willbe/src/command/test.rs

READY : Full string on dry

---

module/move/willbe/src/command/publish.rs
module/move/willbe/src/command/test.rs

READY (willbe) : add colored suggest

---

module/move/willbe/src/entity/version.rs
module/move/willbe/tests/inc/entity/version.rs

Before we updated the highest part of the version, now we will focus on the minor part of the version

READY: (willbe): Logic for bumping of a crate version has been changed

---

module/core/collection_tools/Readme.md
module/core/collection_tools/src/lib.rs
module/core/collection_tools/tests/inc/bmap.rs
module/core/collection_tools/tests/inc/bset.rs
module/core/collection_tools/tests/inc/heap.rs
module/core/collection_tools/tests/inc/hmap.rs
module/core/collection_tools/tests/inc/hset.rs
module/core/collection_tools/tests/inc/list.rs
module/core/collection_tools/tests/inc/vec.rs
module/core/collection_tools/tests/inc/vecd.rs
module/core/collection_tools/tests/tests.rs

The PR fixes the issue with the library not compiling with feature set *default_features* + *no_std*

READY : (collection_tools) : no_std fix

---

module/move/unilang/tests/arg_list_issue.rs

Reveals inability to parse a command that has a list argument.

Unilang arg list issue
