.eslintrc.yml
It enables spacing before keyword of in cycle for-of. Now, ESlint finds error when code looks like :
```js
for( let [ key, value ] of container ] ) 
```
and should not
=> READY : Extend rule for keyword spacing

proto/wtools/abase/l0.test/Str.test.s, proto/wtools/abase/l0/l5/fStr.s
1. Extend test routine `strSplitsQuotedRejoin `.
strSplitsQuotedRejoin, /* qqq xxx : extend, please */
2. Wrote test routine `strSplitsQuotedRejoinOptionOnQuoting`.
onQuoting : null, /* qqq : cover */
3. Implement option::o.pairing
=> READY : Cover `strSplitsQuotedRejoin`

proto/wtools/abase/l0/l1.test/Long.test.s
Values in debug: true vertical sometimes came lesser than debug: false. Please suggest if this is as expected.
=> READY: Performance metrics for long.is has been populated

module/rust/inspect_type/Readme.md, rust/test/automata/wautomata_lib_test.rs, rust/test/mod.rs
Please, notice that the change 
https://github.com/Wandalen/wTools/commit/01e7bca9bca2ccab4849fd6daae18ba0c0f3c719#diff-da98d061a08209a65ad4d2e71b5b6af293b1dfb93fa03cd3ae21ad9e9abecf58R43 
compiles local module with feature `nightly`. It pollutes the feature on dependencies of local module and enabled compilation with unstable features 
```rs
#![ cfg_attr( feature = "nightly", feature( type_name_of_val ) ) ]
``` 
It is the reason of failures
https://github.com/Wandalen/wTools/runs/6378805999?check_suite_focus=true#step:5:35
So, we require to publish module `wtools` and use remote version in module `wautomata`.
=> READY : Fix rust tests

rust/impl/dt/type_constructor/pair.rs
Before, this examples was commented( both )
For type Homopair can be used from array and sample show this
For Pair it can be used too, but it needs to set both generics to one type
=> READY : Fix samples

.gitpod.yml
Small PR to update the rust-analyzer extension to it's new owner in the associated devcontainer.
=> READY: replace `matklad.rust-analyzer` with `rust-lang.rust-analyzer`

rust/impl/ca/ca/grammar/converter.rs
Problem:
User can not implement own help command cuz list of commands is private
=> READY : GrammarConverter commands make public

rust/impl/ca/ca/commands_aggregator/aggregator.rs, rust/impl/ca/ca/commands_aggregator/help.rs, rust/impl/ca/ca/grammar/types.rs, rust/impl/ca/ca/parser/command.rs, rust/impl/ca/ca/parser/entities.rs, rust/test/ca/inc/commands_aggregator/basic.rs, rust/test/ca/inc/parser/command.rs
=> READY : WCA : dot command

module/move/wca/src/ca/facade.rs, module/move/wca/src/ca/parser/command.rs, module/move/wca/src/ca/parser/namespace.rs, module/move/wca/src/ca/parser/program.rs
The current version of wca did not build on version 1.74, with an errors like:
```
error: hidden lifetime parameters in types are deprecated
--> module\move\wca\src\ca\parser\program.rs:31:31
|
|     fn program_fn( &self ) -> ProgramParserFunction
|                               ^^^^^^^^^^^^^^^^^^^^^ expected lifetime parameter
|
help: indicate the anonymous lifetime
|
|     fn program_fn( &self ) -> ProgramParserFunction<'_>
|                                                    ++++
```
=> READY: wca lifetimes fix

module/move/willbe/Cargo.toml, module/move/willbe/src/package/functions.rs
The `.crate` file format has a specific set of files that are ignored, which are:
- `.cargo_vcs_info.json` - this file contains the git sha1 hash that varies between different commits
- `Cargo.toml.orig` - this file can be safely modified because it is used to generate the `Cargo.toml` file automatically, and the `Cargo.toml` file is sufficient to check for changes
=> READY : (willbe) `publish_need` compare file by file and ignore specified list of files

module/move/wca/src/ca/grammar/converter.rs, module/move/wca/src/lib.rs, module/move/wca/tests/inc/executor/command.rs, module/move/wca/tests/inc/grammar/from_command.rs
```rust
wca::Command::former()
.hint( "hint" )
.long_hint( "long_hint" )
.phrase( "command" )
.subject( "This subject is optional", Type::String, true )
.form()
```
accepts both calls: `.command` and `.command with_subject`
=> READY : (wca) optional subjects

module/move/willbe/src/tools/graph.rs, module/move/willbe/tests/inc/graph.rs, module/move/willbe/tests/inc/mod.rs
The commit introduces a new set of unit tests in a new file 'graph.rs' under the tests module. These tests focus on the toposort function in the 'graph.rs' of the tools module, checking scenarios like no dependency, single dependency, multiple dependencies, transitive dependencies and cycles in the graph.
=> READY: (willbe): Add graph tests for toposort function

module/move/wpublisher/src/publisher/commands/init.rs, module/move/wpublisher/src/publisher/commands/list.rs, module/move/wpublisher/tests/publisher/inc/publisher_test.rs
The list command in the publisher module was uncommented in the Routine's construct, activating it for use. Additionally, the error handling in the "list" function was updated from BasicError as expected by Routine. These changes were reflected in the unit tests where successful command execution is now verified.
=> READY:  (wpublisher) Enable list command in publisher module, update error handling

.github/workflows/StandardRustPullRequest.yml
This change updates the StandardRustPullRequest.yml GitHub action workflow, specifically the extraction of the latest commit message. Now, any newline characters are removed from the commit message, ensuring accurate capture of the message for any further processing or output.
=> READY: (workflow): Fix newline issue in commit message extraction

module/blank/willbe_old/Cargo.toml, module/blank/willbe_old/src/willbe_old/commands/each.rs, module/blank/willbe_old/src/willbe_old/commands/end.rs, module/blank/willbe_old/src/willbe_old/commands/package/info.rs, module/blank/willbe_old/src/willbe_old/commands/package/publish.rs, module/blank/willbe_old/src/willbe_old/core/entities/mod.rs, module/blank/willbe_old/src/willbe_old/core/entities/package/metadata.rs, module/blank/willbe_old/src/willbe_old/core/entities/package/mod.rs, module/blank/willbe_old/src/willbe_old/core/entities/package/package.rs, module/blank/willbe_old/src/willbe_old/core/entities/package/verification.rs, module/blank/willbe_old/src/willbe_old/core/entities/utility.rs, module/blank/willbe_old/src/willbe_old/core/entities/workspace.rs, module/blank/willbe_old/src/willbe_old/core/iterators.rs, module/blank/willbe_old/src/willbe_old/files.rs, module/blank/willbe_old/src/willbe_old/willbe_entry.rs, module/blank/willbe_old/src/willbe_old/willbe_lib.rs, module/blank/willbe_old/tests/smoke_test.rs, module/blank/willbe_old/tests/willbe_old/tests/mod.rs, module/move/willbe/Readme.md
This commit introduces several changes to adapt to new module dependencies after a significant codebase reorganization. It includes updating the use of various dependencies from 'wtools' to 'crate', 'mod_interface', 'iter_tools', and 'error_tools'. The code adopting the new 'mod_interface!', 'crate::mod_interface!' and 'error_tools::{ Result, for_app::format_err }' has been extended throughout the code. It also addresses an issue with the test paths and temporarily ignores a smoke test.
=> READY : (willbe_old) : Update module dependencies and fix test paths

module/move/willbe/src/command/run_tests.rs, module/move/willbe/src/endpoint/run_tests.rs
The testing sections of two modules were updated. Fault detection was improved in the `run_tests.rs` file in the `endpoint` module to not only report failures but also consider build errors. Similarly, the `run_tests.rs` file in the `command` module was updated to enable the `with_nightly` flag by default - thus ensuring more thorough testing with the latest versions.
=> READY: (willbe): Improve test failure detection and enable nightly testing by default

module/move/wca/Cargo.toml, module/move/wca/benches/bench.rs
New benchmark tests are added for the wca module. These tests include initializing and running one thousand commands with or without arguments, subjects and properties. The 'Criterion' crate is also added as a development dependency for benchmarking purposes.
=> READY : (willbe): Add benchmark tests for wca module

module/move/willbe/src/command/mod.rs, module/move/willbe/src/command/test.rs, module/move/willbe/src/endpoint/mod.rs, module/move/willbe/src/endpoint/test.rs, module/move/willbe/tests/inc/endpoints/tests_run.rs
'run_tests' Function and References Renamed: To improve the readability and consistency across our codebase, we've renamed the 'run_tests' function to 'test'. This update touches multiple files—anywhere 'run_tests' was referred to or imported, we've updated it to 'test'.
Added Dry Run Mode to Testing Endpoint: We introduced a 'dry run' mode to our test endpoint. This new mode enables a simulated execution of tests without actual running, which is useful for various test planning and development scenarios. We added a 'dry' boolean flag to our 'TestReport' struct—toggling this flag enables you to switch the mode on and off. Also, with this update, we've made several adjustments to how test display outputs are presented, enhancing clarity and readability.
=> READY : (willbe): Refactor Testing Infrastructure and Add Dry Run Mode

Cargo.toml, module/move/willbe/src/command/workspace_new.rs, module/move/willbe/src/endpoint/publish.rs, module/move/willbe/src/endpoint/workflow.rs, module/move/willbe/src/package.rs, module/move/willbe/src/tools/graph.rs, module/move/willbe/src/workspace.rs, module/move/willbe/tests/inc/publish_need.rs, module/test/a/Cargo.toml, module/test/b/Cargo.toml
In this pull request, a new method of handling package publishing in the project is introduced. In the previous system, when a user requested a package to be published, the solution only looked at the package's dependencies and recursively updated them if required. While this approach was functional, it did not account for packages that depended on the requested package. Thus, not every relevant package was getting published.
In this updated system, the dependency graph is now analysed in both directions - not only looking at the package's dependencies but also at its dependents. When a package is requested to be published, the solution identifies its dependencies that require updates, then the dependency graph is reversed. After reversing, all packages that depend on the updated packages …
=> READY : (willbe) Cascade Package Publishing

module/move/willbe/src/test.rs
Now if there is a compilation error, only it is output (`std::err`), and if tests fail, only their output (`std::out`). And also other small changes.
=> NOT READY(willbe): Small fixes

module/move/willbe/src/command/test.rs
Now the `enabled_features` property is working (all the features of the chalk listed in this property will be added to combinations, as described below).
=> READY(willbe/`.test`):Enabled feature fix

Cargo.toml
Problem was in one line in workspace `Cargo.toml`
=> READY(willbe): Publish test fix

module/move/willbe/src/action/publish_diff.rs, module/move/willbe/src/command/mod.rs, module/move/willbe/src/command/publish_diff.rs
I don't know how to get the target directory at runtime.
The `CARGO_TARGET_DIR` environment variable does not exist at runtime.
=> READY : (willbe): Save remote version of the package on `publish.diff`

module/move/willbe/src/entity/diff.rs
The "Cargo.lock" file was added to the PUBLISH_IGNORE_LIST constant. This change ensures that when we are analyzing changes between different commits, the "Cargo.lock" file is ignored alongside ".cargo_vcs_info.json" and "Cargo.toml".
=> READY: (willbe): Add "Cargo.lock" to PUBLISH_IGNORE_LIST constant

module/move/willbe/src/entity/diff.rs
This commit adds a description for `Cargo.lock` in the constant array `PUBLISH_IGNORE_LIST`. It provides an understanding that, `Cargo.lock` is an auto-generated file by Cargo having versions of dependencies which doesn't impact functionality.
=> READY: (willbe): Add details about `Cargo.lock` in PUBLISH_IGNORE_LIST

module/move/wca/src/ca/executor/executor.rs, module/move/wca/src/ca/help.rs, module/move/wca/src/ca/tool/table.rs, module/move/wca/tests/inc/commands_aggregator/basic.rs, module/move/wca/tests/inc/commands_aggregator/help.rs, module/move/wca/tests/inc/parser/command.rs
Renamed HelpGeneratorArgs to HelpGeneratorOptions and made generate_help_content function more accessible for internal crate use. Adjusted how command is parsed within the help and executor modules, notably by handling command prefixes differently. Made minor changes to table formatting for better output and removed unnecessary test cases in command.rs.
=> READY: (wca): Refactor help command handling and clean up tests

.github/workflows/standard_rust_scheduled.yml
This section has never been used in `standard_rust_scheduled.yml`, and got there by mistake from `standard_rust_pull_request.yml`.
This changes should fix workflow.
=> READY : fix workflow

module/move/wca/Cargo.toml, module/move/wca/src/ca/verifier/verifier.rs
Replaced the Eddie library with the TextDistance library for suggesting commands whenever an unknown command is encountered by the system. TextDistance's JaroWinkler algorithm is now being used to find the similarity between the entered command and the available ones. Also updated the related dependencies in Cargo.toml.
=> READY: (wca): Replace Eddie library with TextDistance for command suggestion

module/move/willbe/src/action/readme_health_table_renew.rs
This commit resolves an issue where file path delimiters were incorrectly handled when transitioning between Linux and Windows environments. The code now accurately replaces backslashes with forward slashes before URL encoding, thereby ensuring the filename is correctly split and presented.
=> READY: (willbe): Fix incorrect slash usage in file paths for `readme_health_table_renew` command

module/move/willbe/src/action/publish.rs, module/move/willbe/src/entity/package.rs, module/move/willbe/src/tool/graph.rs
This commit improves error handling and reporting in 'publish.rs', 'package.rs' and 'graph.rs' modules. Specifically, error fallbacks and more descriptive error messages have been introduced. In addition, the 'perform_package_publish' function now returns a tuple containing both a 'PublishReport' and an 'Error', rather than just a 'PublishReport'.
=> READY: (willbe): Improve error handling and reporting in modules

module/move/willbe/src/action/publish_diff.rs
The publish_diff function has been extended to handle multiple crates, enhancing the diffs' reporting capabilities. Additional structures and functions are added to store and display the diffs for each version of the crate. Now, it allows the visualization of changes in different versions of a package and its dependencies by generating a comprehensive report.
=> READY: ( willbe): Extend publish_diff to handle multiple crates

module/move/willbe/src/action/publish.rs, module/move/willbe/src/command/publish.rs, module/move/willbe/src/entity/package.rs
The publish action has been modified to be handle via a publication plan. This adds an intermediary step where the publication steps are defined first in a plan before execution. This change also removed the 'wanted_to_publish' attribute from the PublishReport struct. Displaying as a tree is now also based on roots within the plan.
=> READY: (willbe): Refactor publish action to be able to display the publication plan before execution

module/move/willbe/src/action/list.rs
A 'duplicate' flag was added to the 'ListNodeReport' struct to indicate a node is a duplicate. The process of dependency reporting was restructured with a focus to handle such duplicates more effectively. Also added new functions that merge development dependencies and rearrange duplicates to ensure correct dependency relationships are visualized in reports.
```
wca
├─ error_tools
│  [dev-dependencies]
│  └─ test_tools
│     ├─ data_type
│     │  └─ interval_adapter
│     │     [dev-dependencies]
│     │     └─ test_tools(*)
│     │  [dev-dependencies]
│     │  └─ test_tools(*)
│     ├─ diagnostics_tools
│     │  [dev-dependencies]
│     │  └─ test_tools(*)
│     ├─ error_tools(*)
│     ├─ former
│     │  ├─ collection_tools
│     │  │  [dev-dependencies]
│     │  │  └─ test_tools(*)
│ …
```
=> READY: (willbe): Add duplicate flag and restructure dependency reporting

module/core/derive_tools_meta/src/derive/from.rs, module/core/former_meta/src/derive_former/field_attrs.rs, module/core/former_meta/src/derive_former/struct_attrs.rs
The PR refactors attribute matching to use `match` expressions instead of `if`...`else if`
=> READY : Match attributes

module/core/former/src/collection/binary_heap.rs, module/core/former/src/collection/btree_map.rs, module/core/former/src/collection/btree_set.rs, module/core/former/src/collection/hash_map.rs, module/core/former/src/collection/hash_set.rs, module/core/former/src/collection/linked_list.rs, module/core/former/src/collection/vector.rs, module/core/former/src/collection/vector_deque.rs
The PR ensures that collections are available directly in `collection_tools` (`use collection_tools::<COLLECTION>` without any reexports)
=> READY : (former) : Use direct collection_tools path

module/core/derive_tools_meta/src/derive/from.rs, module/core/former_meta/src/derive_former/field_attrs.rs, module/core/former_meta/src/derive_former/struct_attrs.rs
The PR moves the parsing logic to the `from_meta` function for each `Attribute` type
=> READY : (former) : Refactor `FieldAttribute::from_attrs`

module/core/collection_tools/src/lib.rs, module/core/former/Cargo.toml
The PR should solve the compiler error regarding not used `alloc` crate
=> READY : (collection_tools) : Add enabled directive for crate alloc

module/move/wca/tests/inc/grammar/types.rs
The `try_cast` method on value is designed to convert user input strings into parsed values, such as lists of strings or numbers. However, when converting these parsed values back into their original string representations using the `display` method, the resulting string may not match the original user input.
=>  READY: (wca): Wrote a test that shows an issue related to value displaying

module/core/derive_tools/tests/inc/deref_mut/bounds_inlined.rs, module/core/derive_tools/tests/inc/deref_mut/bounds_mixed.rs, module/core/derive_tools/tests/inc/deref_mut/bounds_where.rs, module/core/derive_tools/tests/inc/deref_mut/enum_named.rs, module/core/derive_tools/tests/inc/deref_mut/enum_tuple.rs, module/core/derive_tools/tests/inc/deref_mut/generics_constants.rs, module/core/derive_tools/tests/inc/deref_mut/generics_constants_default.rs, module/core/derive_tools/tests/inc/deref_mut/generics_lifetimes.rs, module/core/derive_tools/tests/inc/deref_mut/generics_types.rs, module/core/derive_tools/tests/inc/deref_mut/generics_types_default.rs, module/core/derive_tools/tests/inc/deref_mut/name_collisions.rs, module/core/derive_tools/tests/inc/deref_mut/struct_named.rs, module/core/derive_tools/tests/inc/deref_mut/struct_tuple.rs, module/core/derive_tools_meta/src/derive/deref_mut.rs, module/core/derive_tools_meta/src/lib.rs
The PR fixes `deref_mut` tests that don't compile due to disabled `derive_deref` feature.
=> READY : (derive_tools) : Fix deref_mut tests

module/move/willbe/src/action/publish_diff.rs
These messages now are clear, concise, and provide the necessary information to the user about the status of the files.
=> READY: (willbe): Update `.publish.diff` output to make it clearer

module/move/willbe/src/entity/channel.rs
Bug:
unwrap on a `None` value when you have toolchain without `-` in the name(E.g. `solana`)
=> READY (willbe): bugfix: toolchain without `-` in the name

module/core/format_tools/Readme.md, module/core/format_tools/examples/format_tools_trivial.rs
The example did not compile because `WithDebug`, `WithDisplay`, and `to_string_with_fallback` are under the `enabled` feature. The example itself was without features, so when tests were running the tests with the `no_default_features --feature enabled` parameter failed to compile. This PR placed the example code under the `enabled` feature. And now there are no compilation errors.
=> READY(format_tools): fixed tests

.github/workflows/standard_rust_push.yml, module/move/willbe/template/workflow/standard_rust_push.yml
Added IDs for each step in the test job: This allows referencing the result of each step later.
`Check for errors` step: Now checks the outcome status for each step.
If any of them have a value of `failure`, this step will fail the job by returning `exit 1`.
=> READY: checkmate behavior

module/move/unitore/src/command/config.rs
Logic is unchanged. Compiles to the same code. Looks prettier.
=> unitore(suggestion): we can define async command in prettier way

module/core/mod_interface_meta/Cargo.toml
```shell
Note: They might be false-positive.
For example, `cargo-udeps` cannot detect usage of crates that are only used in doc-tests.
To ignore some dependencies, write `package.metadata.cargo-udeps.ignore` in Cargo.toml.
```
=> READY: fix mod_interface_meta for udeps

module/core/format_tools/src/format/output_format/table.rs, module/move/assistant/src/actions/openai.rs, module/move/assistant/src/actions/openai_assistants_list.rs, module/move/assistant/src/actions/openai_files_list.rs, module/move/assistant/src/actions/openai_runs_list.rs, module/move/assistant/src/bin/main.rs, module/move/assistant/src/commands.rs, module/move/assistant/src/commands/openai_assistants.rs, module/move/assistant/src/commands/openai_assistants_list.rs, module/move/assistant/src/commands/openai_files.rs, module/move/assistant/src/commands/openai_files_list.rs, module/move/assistant/src/commands/openai_runs.rs, module/move/assistant/src/commands/openai_runs_list.rs, module/move/assistant/src/lib.rs, module/move/assistant/src/util.rs, module/move/assistant/src/util/display_table.rs
And I also removed line in `format_tools` for debugging
=> READY : Continue work on assistant

module/core/process_tools/src/process.rs
*Turns doc comment into a regular one
=> READY : Remove doc comment in `process_tools`
